import * as Effect$dConsole from "../Effect.Console/index.js";
const $X = () => ({tag: "X"});
const X = /* #__PURE__ */ $X();
const x = X;
const test = dictMonad => dictMonad.Applicative0().pure({x: X});
const main = /* #__PURE__ */ Effect$dConsole.log("Done");
const cA = {c: x1 => v => x1};
const c = dict => dict.c;
const test2 = dictMonad => dictMonad.Applicative0().pure({ccc: cA.c});
export {$X, X, c, cA, main, test, test2, x};
