import { readFileSync, writeFileSync } from "node:fs";

// Resolve from this script so npm --prefix and direct invocation use the same
// source. The generated FFI is embedded by Spago/esbuild, with no runtime I/O.
const runtimePath = new URL("../runtime/runtime.go", import.meta.url);
const ffiPath = new URL("../src/Gopurs/Runtime.js", import.meta.url);

const runtime = readFileSync(runtimePath, "utf8");
const source = "// Generated by tools/embed-runtime.mjs from runtime/runtime.go.\n" +
  "// Edit the Go source, then run npm run build.\n" +
  `export const runtimeGoCode = ${JSON.stringify(runtime)};\n`;

let previous;
try {
  previous = readFileSync(ffiPath, "utf8");
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}

// Preserve the timestamp when the source has not changed, so incremental
// Spago builds do not recompile the FFI unnecessarily.
if (previous !== source) writeFileSync(ffiPath, source);
