import { readFileSync, writeFileSync } from "node:fs";

// Resolve from this script so npm --prefix and direct invocation use the same
// source. The generated FFI is embedded by Spago/esbuild, with no runtime I/O.
const runtimePath = new URL("../runtime/runtime.go", import.meta.url);
const runtime = readFileSync(runtimePath, "utf8");
const header = "// Generated by tools/embed-runtime.mjs from runtime/runtime.go.\n" +
  "// Edit the Go source, then run npm run build.\n";
const sources = [
  ["Runtime.js", header + `export const runtimeGoCode = ${JSON.stringify(runtime)};\n`],
  ["Runtime.go", header + "package Gopurs_Runtime\n\n" +
    `var RuntimeGoCode = ${JSON.stringify(runtime)}\n`],
];

for (const [name, source] of sources) {
  const ffiPath = new URL(`../src/Gopurs/${name}`, import.meta.url);
  let previous;
  try {
    previous = readFileSync(ffiPath, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }

  // Preserve timestamps when unchanged, for both native and JS bootstrap builds.
  if (previous !== source) writeFileSync(ffiPath, source);
}
